/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AppAgenteRouteImport } from './routes/app/agente'
import { Route as AppAgenteAvancadoRouteImport } from './routes/app/agente-avancado'
import { Route as AppCampanhasRouteImport } from './routes/app/campanhas'
import { Route as AppCheckoutRouteImport } from './routes/app/checkout'
import { Route as AppConexaoRouteImport } from './routes/app/conexao'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppContatosRouteImport } from './routes/app/contatos'
import { Route as AppConversasRouteImport } from './routes/app/conversas'
import { Route as AppCrmRouteImport } from './routes/app/crm'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppEquipeRouteImport } from './routes/app/equipe'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppIntegracoesRouteImport } from './routes/app/integracoes'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as CsatTokenRouteImport } from './routes/csat.$token'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAgenteRouteImport } from './routes/demo/agente'
import { Route as DemoCampanhasRouteImport } from './routes/demo/campanhas'
import { Route as DemoConexaoRouteImport } from './routes/demo/conexao'
import { Route as DemoConfiguracoesRouteImport } from './routes/demo/configuracoes'
import { Route as DemoContatosRouteImport } from './routes/demo/contatos'
import { Route as DemoConversasRouteImport } from './routes/demo/conversas'
import { Route as DemoCrmRouteImport } from './routes/demo/crm'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoEquipeRouteImport } from './routes/demo/equipe'
import { Route as DemoFinanceiroRouteImport } from './routes/demo/financeiro'
import { Route as DemoIntegracoesRouteImport } from './routes/demo/integracoes'
import { Route as DemoRelatoriosRouteImport } from './routes/demo/relatorios'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as MasterAssinaturasRouteImport } from './routes/master/assinaturas'
import { Route as MasterConfiguracoesRouteImport } from './routes/master/configuracoes'
import { Route as MasterEmpresasRouteImport } from './routes/master/empresas'
import { Route as MasterNovaEmpresaRouteImport } from './routes/master/nova-empresa'
import { Route as MasterPainelRouteImport } from './routes/master/painel'
import { Route as MasterPlanosRouteImport } from './routes/master/planos'
import { Route as ApiPublicAuthEmailHookRouteImport } from './routes/api/public/auth-email-hook'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google-callback'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing/webhook'
import { Route as ApiPublicHooksProcessCampaignsRouteImport } from './routes/api/public/hooks/process-campaigns'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteAvancadoRoute = AppAgenteAvancadoRouteImport.update({
  id: '/agente-avancado',
  path: '/agente-avancado',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppConexaoRoute = AppConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConversasRoute = AppConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const CsatTokenRoute = CsatTokenRouteImport.update({
  id: '/csat/$token',
  path: '/csat/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgenteRoute = DemoAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCampanhasRoute = DemoCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConexaoRoute = DemoConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConfiguracoesRoute = DemoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoContatosRoute = DemoContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConversasRoute = DemoConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCrmRoute = DemoCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEquipeRoute = DemoEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DemoRoute,
} as any)
const DemoIntegracoesRoute = DemoIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRelatoriosRoute = DemoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => DemoRoute,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterEmpresasRoute = MasterEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovaEmpresaRoute = MasterNovaEmpresaRouteImport.update({
  id: '/nova-empresa',
  path: '/nova-empresa',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPlanosRoute = MasterPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => MasterRoute,
} as any)
const ApiPublicAuthEmailHookRoute = ApiPublicAuthEmailHookRouteImport.update({
  id: '/api/public/auth-email-hook',
  path: '/api/public/auth-email-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google-callback',
  path: '/api/public/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessCampaignsRoute =
  ApiPublicHooksProcessCampaignsRouteImport.update({
    id: '/api/public/hooks/process-campaigns',
    path: '/api/public/hooks/process-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/agente-avancado': typeof AppAgenteAvancadoRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/campanhas': typeof DemoCampanhasRoute
  '/demo/conexao': typeof DemoConexaoRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/contatos': typeof DemoContatosRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/integracoes': typeof DemoIntegracoesRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/demo/': typeof DemoIndexRoute
  '/master/': typeof MasterIndexRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/agente-avancado': typeof AppAgenteAvancadoRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/campanhas': typeof DemoCampanhasRoute
  '/demo/conexao': typeof DemoConexaoRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/contatos': typeof DemoContatosRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/integracoes': typeof DemoIntegracoesRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/demo': typeof DemoIndexRoute
  '/master': typeof MasterIndexRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/agente-avancado': typeof AppAgenteAvancadoRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/campanhas': typeof DemoCampanhasRoute
  '/demo/conexao': typeof DemoConexaoRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/contatos': typeof DemoContatosRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/integracoes': typeof DemoIntegracoesRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/demo/': typeof DemoIndexRoute
  '/master/': typeof MasterIndexRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/privacidade'
    | '/reembolso'
    | '/reset-senha'
    | '/termos'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/agente-avancado'
    | '/app/campanhas'
    | '/app/checkout'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/csat/$token'
    | '/demo/agente'
    | '/demo/campanhas'
    | '/demo/conexao'
    | '/demo/configuracoes'
    | '/demo/contatos'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/integracoes'
    | '/demo/relatorios'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/master/planos'
    | '/demo/'
    | '/master/'
    | '/api/public/auth-email-hook'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/entrar'
    | '/esqueci-senha'
    | '/privacidade'
    | '/reembolso'
    | '/reset-senha'
    | '/termos'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/agente-avancado'
    | '/app/campanhas'
    | '/app/checkout'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/csat/$token'
    | '/demo/agente'
    | '/demo/campanhas'
    | '/demo/conexao'
    | '/demo/configuracoes'
    | '/demo/contatos'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/integracoes'
    | '/demo/relatorios'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/master/planos'
    | '/demo'
    | '/master'
    | '/api/public/auth-email-hook'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/privacidade'
    | '/reembolso'
    | '/reset-senha'
    | '/termos'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/agente-avancado'
    | '/app/campanhas'
    | '/app/checkout'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/csat/$token'
    | '/demo/agente'
    | '/demo/campanhas'
    | '/demo/conexao'
    | '/demo/configuracoes'
    | '/demo/contatos'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/integracoes'
    | '/demo/relatorios'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/master/planos'
    | '/demo/'
    | '/master/'
    | '/api/public/auth-email-hook'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  ResetSenhaRoute: typeof ResetSenhaRoute
  TermosRoute: typeof TermosRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  CsatTokenRoute: typeof CsatTokenRoute
  ApiPublicAuthEmailHookRoute: typeof ApiPublicAuthEmailHookRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicHooksProcessCampaignsRoute: typeof ApiPublicHooksProcessCampaignsRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agente': {
      id: '/app/agente'
      path: '/agente'
      fullPath: '/app/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente-avancado': {
      id: '/app/agente-avancado'
      path: '/agente-avancado'
      fullPath: '/app/agente-avancado'
      preLoaderRoute: typeof AppAgenteAvancadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conexao': {
      id: '/app/conexao'
      path: '/conexao'
      fullPath: '/app/conexao'
      preLoaderRoute: typeof AppConexaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contatos': {
      id: '/app/contatos'
      path: '/contatos'
      fullPath: '/app/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversas': {
      id: '/app/conversas'
      path: '/conversas'
      fullPath: '/app/conversas'
      preLoaderRoute: typeof AppConversasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes': {
      id: '/app/integracoes'
      path: '/integracoes'
      fullPath: '/app/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/csat/$token': {
      id: '/csat/$token'
      path: '/csat/$token'
      fullPath: '/csat/$token'
      preLoaderRoute: typeof CsatTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agente': {
      id: '/demo/agente'
      path: '/agente'
      fullPath: '/demo/agente'
      preLoaderRoute: typeof DemoAgenteRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/campanhas': {
      id: '/demo/campanhas'
      path: '/campanhas'
      fullPath: '/demo/campanhas'
      preLoaderRoute: typeof DemoCampanhasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/conexao': {
      id: '/demo/conexao'
      path: '/conexao'
      fullPath: '/demo/conexao'
      preLoaderRoute: typeof DemoConexaoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/configuracoes': {
      id: '/demo/configuracoes'
      path: '/configuracoes'
      fullPath: '/demo/configuracoes'
      preLoaderRoute: typeof DemoConfiguracoesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/contatos': {
      id: '/demo/contatos'
      path: '/contatos'
      fullPath: '/demo/contatos'
      preLoaderRoute: typeof DemoContatosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/conversas': {
      id: '/demo/conversas'
      path: '/conversas'
      fullPath: '/demo/conversas'
      preLoaderRoute: typeof DemoConversasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/crm': {
      id: '/demo/crm'
      path: '/crm'
      fullPath: '/demo/crm'
      preLoaderRoute: typeof DemoCrmRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/equipe': {
      id: '/demo/equipe'
      path: '/equipe'
      fullPath: '/demo/equipe'
      preLoaderRoute: typeof DemoEquipeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/financeiro': {
      id: '/demo/financeiro'
      path: '/financeiro'
      fullPath: '/demo/financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/integracoes': {
      id: '/demo/integracoes'
      path: '/integracoes'
      fullPath: '/demo/integracoes'
      preLoaderRoute: typeof DemoIntegracoesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/relatorios': {
      id: '/demo/relatorios'
      path: '/relatorios'
      fullPath: '/demo/relatorios'
      preLoaderRoute: typeof DemoRelatoriosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/assinaturas': {
      id: '/master/assinaturas'
      path: '/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/empresas': {
      id: '/master/empresas'
      path: '/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof MasterEmpresasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/nova-empresa': {
      id: '/master/nova-empresa'
      path: '/nova-empresa'
      fullPath: '/master/nova-empresa'
      preLoaderRoute: typeof MasterNovaEmpresaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/planos': {
      id: '/master/planos'
      path: '/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof MasterPlanosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/api/public/auth-email-hook': {
      id: '/api/public/auth-email-hook'
      path: '/api/public/auth-email-hook'
      fullPath: '/api/public/auth-email-hook'
      preLoaderRoute: typeof ApiPublicAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-callback': {
      id: '/api/public/google-callback'
      path: '/api/public/google-callback'
      fullPath: '/api/public/google-callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-campaigns': {
      id: '/api/public/hooks/process-campaigns'
      path: '/api/public/hooks/process-campaigns'
      fullPath: '/api/public/hooks/process-campaigns'
      preLoaderRoute: typeof ApiPublicHooksProcessCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppAgenteAvancadoRoute: typeof AppAgenteAvancadoRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppConexaoRoute: typeof AppConexaoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppConversasRoute: typeof AppConversasRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppAgenteAvancadoRoute: AppAgenteAvancadoRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppConexaoRoute: AppConexaoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppConversasRoute: AppConversasRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAgenteRoute: typeof DemoAgenteRoute
  DemoCampanhasRoute: typeof DemoCampanhasRoute
  DemoConexaoRoute: typeof DemoConexaoRoute
  DemoConfiguracoesRoute: typeof DemoConfiguracoesRoute
  DemoContatosRoute: typeof DemoContatosRoute
  DemoConversasRoute: typeof DemoConversasRoute
  DemoCrmRoute: typeof DemoCrmRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoEquipeRoute: typeof DemoEquipeRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoIntegracoesRoute: typeof DemoIntegracoesRoute
  DemoRelatoriosRoute: typeof DemoRelatoriosRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAgenteRoute: DemoAgenteRoute,
  DemoCampanhasRoute: DemoCampanhasRoute,
  DemoConexaoRoute: DemoConexaoRoute,
  DemoConfiguracoesRoute: DemoConfiguracoesRoute,
  DemoContatosRoute: DemoContatosRoute,
  DemoConversasRoute: DemoConversasRoute,
  DemoCrmRoute: DemoCrmRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoEquipeRoute: DemoEquipeRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoIntegracoesRoute: DemoIntegracoesRoute,
  DemoRelatoriosRoute: DemoRelatoriosRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterEmpresasRoute: typeof MasterEmpresasRoute
  MasterNovaEmpresaRoute: typeof MasterNovaEmpresaRoute
  MasterPainelRoute: typeof MasterPainelRoute
  MasterPlanosRoute: typeof MasterPlanosRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterEmpresasRoute: MasterEmpresasRoute,
  MasterNovaEmpresaRoute: MasterNovaEmpresaRoute,
  MasterPainelRoute: MasterPainelRoute,
  MasterPlanosRoute: MasterPlanosRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  ResetSenhaRoute: ResetSenhaRoute,
  TermosRoute: TermosRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  CsatTokenRoute: CsatTokenRoute,
  ApiPublicAuthEmailHookRoute: ApiPublicAuthEmailHookRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicHooksProcessCampaignsRoute: ApiPublicHooksProcessCampaignsRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
